import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Main from "../components/Main";
import { useUser } from "../Hooks/useUser";
import { GetServerSideProps } from "next";
import { dehydrate, QueryClient } from "@tanstack/react-query";
import Loader from "../components/Common/Loader";
import { getPreferencesPosts } from "../utils/axios";

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery([`preferencesPosts`], () =>
    getPreferencesPosts(ctx.req.headers.cookie)
  );

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};

export default function Home() {
  const { isLoadingUser, user, authenticated } = useUser({
    redirectTo: "/start",
    redirectIfFound: false,
  });

  if (isLoadingUser || !user || !authenticated)
    return (
      <div className="h-screen w-screen">
        <Loader />
      </div>
    );

  return (
    <div className="flex min-h-screen flex-col bg-gray-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header profile_id={user.profile_id} />
      <Main />
      <Footer profile_id={user.profile_id} />
    </div>
  );
}
